In [19]:
from PIL import Image, ImageFilter
import numpy as np
from scipy import ndimage
from matplotlib import pyplot as plt

try:
    # загружаем изображение с жесткого диска
#     original = Image.open("../images/tussaint.jpg").convert('L')
#     original = Image.open("../images/graytussaint100.jpg")
    original = Image.open("../../build/convolution/cpu-convolved.jpg")
    cimg = Image.open("../../build/convolution/cuda-convolved.jpg")
except FileNotFoundError:
    print("Файл не найден")

# original.save('graytussaint.jpg')
pic1 = np.array(original)
pic2 = np.array(cimg)
# gaus_kernel = np.array(([1,2,1],[2,4,2],[1,2,1]))*(1/16)
# edge_kernel = np.array(([1,0,-1],[0,0,0],[-1,0,1]))

#Test convolution between C++ and Python\
print(pic1)
print(pic2)
print(np.array_equal(pic1,pic2))
# row = np.array([11, 0, 4, 10, 9, 14, 6, 14, 15, 7, 10, 11, 15, 2, 2, 14, 9])
# print(np.outer(row,row))
# print(pic2)
# convolved = ndimage.convolve(original,kernel,mode='constant',cval=0.0)
# convolved_img = Image.fromarray(convolved)
# cimg = np.array(convolved_img)
# print(np.array(Image.open("graytussaint-blured.jpg")))
# print(convolved)
# print(cimg)
# convolved_img.save('gtblured.jpg',quality=100)
# original.save('graytussaint100.jpg',quality=100)
# print(np.array(Image.open("gtblured.jpg")))
# print(np.array(Image.open("gtblured.jpg")))
# 11 0 4 10 9 14 6 14 15 7 10 11 15 2 2 14 9 = 153

[[41 44 49 ... 67 64 55]
 [44 48 53 ... 73 69 59]
 [49 53 60 ... 81 77 66]
 ...
 [51 54 59 ... 82 77 66]
 [47 51 56 ... 77 72 62]
 [40 43 49 ... 66 62 52]]
[[41 44 49 ... 67 64 55]
 [44 48 53 ... 73 69 59]
 [49 53 60 ... 81 77 66]
 ...
 [51 54 59 ... 82 77 66]
 [47 51 56 ... 77 72 62]
 [40 43 49 ... 66 62 52]]
False
